#!/usr/bin/env python3
"""
Test script demonstrating the observe action functionality.

This script shows how the observe action can be used to pause execution,
update world state through object tracking, and resume with newly decomposed
actions that account for state changes.

Usage:
    python examples/test_observe_action.py --dry-run
"""

import asyncio
import os
import sys
from pathlib import Path

# Add project root to path
project_root = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(project_root))

from src.task_motion_planner import TaskAndMotionPlanner, TAMPConfig


async def test_observe_action():
    """
    Test the observe action with a simulated multi-step task.

    The plan will be:
    1. pick(block1)
    2. place(block1, block2)
    3. observe  # <-- Pause, update world state
    4. pick(block3)
    5. place(block3, block2)
    """

    # Check API key
    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key:
        print("Error: GEMINI_API_KEY not set")
        print("Set it with: export GEMINI_API_KEY=your_key")
        return 1

    # Configure TAMP
    output_dir = project_root / "outputs" / "observe_action_test"
    output_dir.mkdir(parents=True, exist_ok=True)

    config = TAMPConfig(
        api_key=api_key,
        state_dir=output_dir,
        orchestrator_model="gemini-robotics-er-1.5-preview",
        decomposer_model="gemini-robotics-er-1.5-preview",
        update_interval=2.0,
        min_observations=3,
        solver_backend="pyperplan",
        dry_run_default=True,  # Safe dry-run by default
    )

    tamp = TaskAndMotionPlanner(config)

    print("="*70)
    print("OBSERVE ACTION TEST")
    print("="*70)
    print()
    print("This test demonstrates the observe action functionality:")
    print("1. Initial actions are decomposed with current world state")
    print("2. When 'observe' is encountered, execution pauses")
    print("3. Object tracking updates the world state")
    print("4. Remaining actions are decomposed with updated state")
    print("5. Execution continues with fresh observations")
    print()
    print("="*70)
    print()

    try:
        # Initialize
        await tamp.initialize()

        # Set up a test task that benefits from observe
        # Note: The actual PDDL plan with 'observe' would need to be
        # generated by the planner. This test demonstrates the execution
        # flow when such a plan exists.
        task = (
            "Pick up block1, place it on block2, then observe the scene, "
            "then pick up block3 and place it on block2"
        )

        print(f"Task: {task}")
        print()

        # For a real test, you would:
        # 1. Run perception to detect blocks
        # 2. Generate a PDDL plan that includes an 'observe' action
        # 3. Execute the plan

        print("NOTE: To fully test this feature, you need:")
        print("  1. A PDDL domain that includes an 'observe' action")
        print("  2. A problem that results in a plan with observe in it")
        print("  3. Objects in the scene to detect and manipulate")
        print()
        print("The observe action will automatically:")
        print("  - Pause after executing actions before 'observe'")
        print("  - Run object tracking to update world state (~5s)")
        print("  - Re-decompose remaining actions with updated state")
        print("  - Continue execution")
        print()
        print("Example PDDL plan with observe:")
        print("  1. (pick gripper block1)")
        print("  2. (place gripper block1 block2)")
        print("  3. (observe)")
        print("  4. (pick gripper block3)")
        print("  5. (place gripper block3 block2)")
        print()

        # The actual execution would happen via:
        # result = await tamp.plan_and_execute_task(task, dry_run=True)

        print("✓ Test setup complete")
        print()
        print("To run a full integration test:")
        print("  1. Set up a scene with multiple blocks")
        print("  2. Create a PDDL domain with the 'observe' action")
        print("  3. Run: python examples/tamp_demo.py --task \"<your task>\"")

    except Exception as e:
        print(f"✗ Error: {e}")
        import traceback
        traceback.print_exc()
        return 1
    finally:
        await tamp.shutdown()

    return 0


if __name__ == "__main__":
    sys.exit(asyncio.run(test_observe_action()))
