"""
Clutter Domain Module — L2 Predicate Vocabulary and Grounding Rules

Pre-loads the clutter manipulation predicate library into the DKB and
provides a ClutterGrounder that evaluates each predicate's grounding rule
against a live Ψ snapshot (DetectedObjectRegistry + per-object perception
outputs).

Usage
-----
    from src.planning.clutter_module import load_clutter_module, ClutterGrounder

    # Once at startup — idempotent, safe to call again after DKB reload
    load_clutter_module(dkb)

    # Each planning cycle, after perception has updated Ψ
    grounder = ClutterGrounder(registry)
    true_facts = grounder.ground_all()
    # → [("stable-on", ["red_block_1", "table_1"]), ...]

Predicate catalogue (§3.1)
--------------------------
Sensed (conservative FALSE until check-X sensing action runs):
    access-clear(?obj)
    obstructs(?blocker, ?target)
    displaceable(?obj)
    space-available(?surface, ?obj)
    supports(?lower, ?upper)
    removal-safe(?obj)
    visible(?obj)
    occluded-by(?target, ?blocker)

State (grounded directly from Ψ at L5 init):
    stable-on(?obj, ?surface)

Each sensed predicate has a corresponding checked-* variant auto-generated
by _repair_l2_auto() in LayeredDomainGenerator — not listed here.
"""

from __future__ import annotations

import logging
from typing import TYPE_CHECKING, Any, Dict, List, Optional, Set, Tuple  # noqa: F401

import numpy as np

if TYPE_CHECKING:
    from ..perception.object_registry import DetectedObjectRegistry

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Threshold constants matching §3.2 grounding rules
# ---------------------------------------------------------------------------

_GRASPABILITY_THRESHOLD: float = 0.5    # access-clear: graspability_score >
_IMPROVED_CLEARANCE_LOW: float = 0.3    # improved-clearance: lower bound (exclusive)
_IMPROVED_CLEARANCE_HIGH: float = 0.5   # improved-clearance: upper bound (exclusive)
_VISIBILITY_THRESHOLD: float = 0.6      # visible: visible_fraction >

# Substrings used to identify surface/support objects by object_type.
# Checked with `any(kw in obj.object_type.lower() for kw in _SURFACE_KEYWORDS)`.
_SURFACE_KEYWORDS: Tuple[str, ...] = (
    "surface", "table", "shelf", "tray", "counter", "desk", "floor", "ground",
)

# ---------------------------------------------------------------------------
# Clutter module predicate definitions
# ---------------------------------------------------------------------------

# Each entry: (name, signature, type_classification, grounding_rule_summary)
_CLUTTER_PREDICATES: List[Tuple[str, str, str, str]] = [
    # Access / obstruction
    (
        "access-clear",
        "(?obj - object)",
        "sensed",
        "graspability_score > 0.5 AND any grasp_compatible corridor",
    ),
    (
        "obstructs",
        "(?blocker - object ?target - object)",
        "sensed",
        "?blocker in obstructing_objects of any blocked corridor of ?target",
    ),
    (
        "displaceable",
        "(?obj - object)",
        "sensed",
        "stability_score > 0.7 AND removal_consequence != cascade",
    ),
    # Placement
    (
        "space-available",
        "(?surface - surface ?obj - object)",
        "sensed",
        "any free_region.max_inscribed_circle >= obj footprint radius",
    ),
    # Stability / support
    (
        "supports",
        "(?lower - object ?upper - object)",
        "sensed",
        "(?lower, ?upper) in contact_graph.support_tree",
    ),
    (
        "removal-safe",
        "(?obj - object)",
        "sensed",
        "contact_graph.removal_consequences[?obj] == stable",
    ),
    (
        "stable-on",
        "(?obj - object ?surface - surface)",
        "object_state",
        "contact_graph supporting edge from ?surface to ?obj",
    ),
    (
        "spatial-change-occurred",
        "",
        "object_state",
        "set TRUE by displace/push-aside; cleared by T5 re-grounding hook",
    ),
    # Visibility
    (
        "visible",
        "(?obj - object)",
        "sensed",
        "occlusion_map.per_object_visibility[?obj].visible_fraction > 0.6",
    ),
    (
        "occluded-by",
        "(?target - object ?blocker - object)",
        "sensed",
        "?blocker in occlusion_map.per_object_visibility[?target].occluding_objects",
    ),
]

# Sensed predicates that need checked-* variants (auto-generated by L2 repair)
CLUTTER_SENSED_PREDICATE_NAMES: List[str] = [
    entry[0] for entry in _CLUTTER_PREDICATES
    if entry[2] == "sensed"
]


# ---------------------------------------------------------------------------
# Pre-loaded L3 action schemas (§4.1)
# ---------------------------------------------------------------------------

# Only genuinely new manipulation types are pre-loaded. Sensing actions
# (check-access-clear, etc.) are auto-generated by _repair_l2_auto() from the
# sensed predicate definitions above — pre-loading them would bypass L3
# consistency guarantees.

_CLUTTER_ACTIONS: List[Dict] = [
    {
        # Canonical pick — overrides any LLM-generated variant to guarantee
        # (on ?obj ?surface) precondition and correct holding/on effects.
        "name": "pick",
        "parameters": "(?obj - object ?surface - object)",
        "precondition": (
            "(and "
            "(hand-empty) "
            "(gripper-empty) "
            "(stable-on ?obj ?surface) "
            "(object-graspable ?obj) "
            "(access-clear ?obj) "
            "(removal-safe ?obj))"
        ),
        "effect": (
            "(and "
            "(holding ?obj) "
            "(not (hand-empty)) "
            "(not (gripper-empty)) "
            "(not (stable-on ?obj ?surface)) "
            "(not (on ?obj ?surface)) "
            "(not (object-at ?obj ?surface)) "
            "(spatial-change-occurred))"
        ),
        "description": (
            "Grasp an object from a surface and lift it into a held state. "
            "The gripper must be empty and the object must be access-clear. "
            "Primitive sequence: move_gripper_to_pose to the grasp contact point "
            "on ?obj → close_gripper → retract_gripper to lift clear of ?surface. "
            "Use pointing_guidance to describe the exact grasp contact region on ?obj "
            "(e.g. 'the cylindrical body of the cup just below the rim'). "
            "Choose approach_direction based on object geometry: top_down for flat-topped "
            "or open objects, side for tall/narrow objects or when overhead clearance is limited."
        ),
    },
    {
        "name": "displace",
        # ?to is omitted — the executor resolves the destination at runtime.
        "parameters": "(?obj - object ?from - object)",
        "precondition": (
            "(and "
            "(object-at ?obj ?from) "
            "(displaceable ?obj) "
            "(removal-safe ?obj) "
            "(gripper-empty))"
        ),
        "effect": (
            "(and "
            "(not (object-at ?obj ?from)) "
            "(not (stable-on ?obj ?from)) "
            "(not (on ?obj ?from)) "
            "(spatial-change-occurred))"
        ),
        "description": (
            "Grasp ?obj and move it away from ?from to clear the area — the destination "
            "is chosen by the executor at runtime (typically to the side or rear of the workspace). "
            "Primitive sequence: move_gripper_to_pose to a stable grasp point on ?obj → "
            "close_gripper → move_gripper_to_pose to a clear drop zone → open_gripper → retract_gripper. "
            "Use pointing_guidance to describe the most stable grasp region on ?obj "
            "(e.g. 'the widest stable part of the box where a pinch grip can lift it'). "
            "Prefer top_down approach unless overhead clearance is blocked."
        ),
    },
    {
        "name": "push-aside",
        "parameters": "(?obj - object ?surface - object)",
        "precondition": (
            "(and "
            "(on ?obj ?surface) "
            "(displaceable ?obj) "
            "(removal-safe ?obj) "
            "(gripper-empty))"
        ),
        "effect": (
            "(and "
            "(not (on ?obj ?surface)) "
            "(not (object-at ?obj ?surface)) "
            "(spatial-change-occurred))"
        ),
        "description": (
            "Slide or nudge ?obj laterally across ?surface without fully grasping it — "
            "the object stays on the surface but moves out of the target area. "
            "Primitive sequence: move_gripper_to_pose to the push contact point on the side "
            "of ?obj facing the direction of displacement → push_pull with force_direction='parallel'. "
            "Use pointing_guidance to describe the push contact surface "
            "(e.g. 'the flat side face of the rubber duck facing the robot, to push it left'). "
            "approach_direction should be side since contact is on a vertical face of the object."
        ),
    },
    {
        # Clears symbolic obstruction state for a specific blocker→target pair.
        # Requires (obstructs ?blocker ?target) and that ?blocker is displaceable
        # and removal-safe — meaning the planner must first verify those sensed
        # predicates hold before scheduling this action. The physical displacement
        # is handled by displace/push-aside; this updates the obstruction graph.
        "name": "push-aside-obstruction",
        "parameters": "(?blocker - object ?target - object)",
        "precondition": (
            "(and "
            "(obstructs ?blocker ?target) "
            "(displaceable ?blocker) "
            "(removal-safe ?blocker) "
            "(gripper-empty))"
        ),
        "effect": (
            "(and "
            "(access-clear ?target) "
            "(not (obstructs ?blocker ?target)) "
            "(not (on ?blocker ?target)) "
            "(not (object-at ?blocker ?target)) "
            "(spatial-change-occurred))"
        ),
        "description": (
            "Move ?blocker out of the way so that ?target becomes accessible — physically "
            "identical to displace or push-aside but also updates the symbolic obstruction graph "
            "(marks ?target as access-clear and removes the obstructs fact). "
            "Primitive sequence: same as displace — move_gripper_to_pose to a stable grasp "
            "point on ?blocker → close_gripper → move_gripper_to_pose to a clear drop zone → "
            "open_gripper → retract_gripper. "
            "Use pointing_guidance to describe the grasp region on ?blocker. "
            "Prefer top_down approach unless overhead clearance is blocked."
        ),
    },
]

# ---------------------------------------------------------------------------
# DKB loader
# ---------------------------------------------------------------------------

def load_clutter_module(dkb: "DomainKnowledgeBase") -> None:  # type: ignore[name-defined]
    """Load the clutter predicate library into the DKB predicate store.

    Idempotent — existing entries are updated in place (usage_count preserved).
    Call once at startup after dkb.load().

    Args:
        dkb: A DomainKnowledgeBase instance (already loaded).
    """
    loaded = 0
    for name, params, cls, rule in _CLUTTER_PREDICATES:
        sig = f"({name} {params})" if params else f"({name})"
        existing = dkb._predicates.get(name, {})
        dkb._predicates[name] = {
            "signature": sig,
            "type_classification": cls,
            "grounding_rule": rule,
            "domain_module": "clutter",
            "usage_count": existing.get("usage_count", 0),
            "last_task": existing.get("last_task", ""),
        }
        loaded += 1

    # Register pre-loaded action schemas into the DKB action library
    for action in _CLUTTER_ACTIONS:
        name = action["name"]
        existing = dkb._actions.get(name, {})
        dkb._actions[name] = {
            **{k: v for k, v in action.items() if k != "name"},
            "domain_module": "clutter",
            "usage_count": existing.get("usage_count", 0),
        }

    logger.info(
        "load_clutter_module: loaded %d predicate definitions and %d action schemas into DKB",
        loaded, len(_CLUTTER_ACTIONS),
    )


def get_clutter_action_schemas() -> List[Dict]:
    """Return the pre-loaded L3 action schemas for the clutter domain."""
    return list(_CLUTTER_ACTIONS)


def get_clutter_predicate_signatures() -> List[str]:
    """Return full PDDL-style signatures for all clutter predicates."""
    return [
        f"({name} {params})" if params else f"({name})"
        for name, params, _, _ in _CLUTTER_PREDICATES
    ]


def get_clutter_type_classifications() -> Dict[str, str]:
    """Return {predicate_name: type_classification} for all clutter predicates."""
    return {name: cls for name, _, cls, _ in _CLUTTER_PREDICATES}


# ---------------------------------------------------------------------------
# SymbolicState — lightweight in-memory PDDL fact store
# ---------------------------------------------------------------------------

class SymbolicState:
    """Minimal in-memory PDDL fact store for post-execution hook bookkeeping.

    Facts are represented as frozensets of (predicate_name, args_tuple).
    The store supports add, remove, and membership tests used by the
    post-displacement hook to invalidate stale checked-* predicates and
    inject freshly grounded ones.
    """

    def __init__(self) -> None:
        self._facts: Set[Tuple[str, Tuple[str, ...]]] = set()

    def add(self, predicate: str, *args: str) -> None:
        self._facts.add((predicate, tuple(args)))

    def remove(self, predicate: str, *args: str) -> None:
        self._facts.discard((predicate, tuple(args)))

    def remove_matching(self, predicate: str, *args: Optional[str]) -> None:
        """Remove all facts matching predicate where None args act as wildcards."""
        to_remove = set()
        for fact in self._facts:
            if fact[0] != predicate:
                continue
            if len(fact[1]) != len(args):
                continue
            if all(a is None or a == fa for a, fa in zip(args, fact[1])):
                to_remove.add(fact)
        self._facts -= to_remove

    def contains(self, predicate: str, *args: str) -> bool:
        return (predicate, tuple(args)) in self._facts

    def all_facts(self) -> List[Tuple[str, Tuple[str, ...]]]:
        return list(self._facts)

    def __len__(self) -> int:
        return len(self._facts)


# ---------------------------------------------------------------------------
# PostDisplacementHook — re-grounds clearance after displace / push-aside
# ---------------------------------------------------------------------------

# Spatial radius within which neighbors are considered affected (metres).
_NEIGHBOR_RADIUS_M: float = 0.30

class PostDisplacementHook:
    """Re-grounds clearance predicates for spatially affected objects after
    a displace or push-aside action executes.

    Implements spec §4.3:
    1. Find neighbors within _NEIGHBOR_RADIUS_M of the displaced object.
    2. Invalidate checked-access-clear and checked-obstructs for each neighbor
       in the symbolic state.
    3. Re-run compute_clearance_profile on each neighbor using fresh Ψ.
    4. Inject TRUE/FALSE access-clear and obstructs facts based on new profiles.
    5. Return True if the remaining plan is still valid, False if replanning needed.

    Usage:
        hook = PostDisplacementHook(registry, camera_intrinsics, cam_position, cam_rotation)
        still_valid = hook.run(
            displaced_obj_id="mug_1",
            symbolic_state=sym_state,
            remaining_plan=plan[step_idx + 1:],
        )
        if not still_valid:
            new_plan = await replan_fn()
    """

    def __init__(
        self,
        registry: "DetectedObjectRegistry",
        camera_intrinsics: Optional[Any] = None,
        cam_position: Optional[Any] = None,
        cam_rotation: Optional[Any] = None,
        logger: Optional[logging.Logger] = None,
    ) -> None:
        self._registry = registry
        self._intrinsics = camera_intrinsics
        self._cam_position = cam_position
        self._cam_rotation = cam_rotation
        self._log = logger or logging.getLogger(__name__)

    def run(
        self,
        displaced_obj_id: str,
        symbolic_state: SymbolicState,
        remaining_plan: List[str],
    ) -> bool:
        """Execute the post-displacement grounding update.

        Args:
            displaced_obj_id: Object that was displaced/pushed.
            symbolic_state: Live symbolic state to mutate.
            remaining_plan: Steps still to execute (used for validity check).

        Returns:
            True if remaining plan is still executable, False if replanning needed.
        """
        affected = self._find_affected_neighbors(displaced_obj_id)
        self._log.info(
            "[PostDisplacementHook] displaced=%s  affected neighbors: %s",
            displaced_obj_id, affected,
        )

        for obj_id in affected:
            self._invalidate_checked(obj_id, displaced_obj_id, symbolic_state)
            self._reground_clearance(obj_id, symbolic_state)

        # Clear the spatial-change-occurred flag now that re-grounding is done
        symbolic_state.remove("spatial-change-occurred")

        return self._plan_still_valid(symbolic_state, remaining_plan)

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _find_affected_neighbors(self, displaced_obj_id: str) -> List[str]:
        """Return object IDs within _NEIGHBOR_RADIUS_M of the displaced object."""
        displaced = self._registry.get_object(displaced_obj_id)
        if displaced is None or displaced.position_3d is None:
            # Fall back to all objects if we can't locate the displaced one
            return [
                o.object_id for o in self._registry.get_all_objects()
                if o.object_id != displaced_obj_id
            ]

        center = np.asarray(displaced.position_3d, float)
        affected: List[str] = []
        for obj in self._registry.get_all_objects():
            if obj.object_id == displaced_obj_id:
                continue
            if obj.position_3d is None:
                affected.append(obj.object_id)
                continue
            dist = float(np.linalg.norm(np.asarray(obj.position_3d, float) - center))
            if dist <= _NEIGHBOR_RADIUS_M:
                affected.append(obj.object_id)
        return affected

    def _invalidate_checked(
        self, obj_id: str, displaced_obj_id: str, sym: SymbolicState
    ) -> None:
        """Remove stale checked-* predicates for obj_id from symbolic state."""
        sym.remove("checked-access-clear", obj_id)
        sym.remove_matching("checked-obstructs", displaced_obj_id, obj_id)
        sym.remove_matching("checked-obstructs", None, obj_id)
        self._log.debug(
            "[PostDisplacementHook] invalidated checked predicates for %s", obj_id
        )

    def _reground_clearance(self, obj_id: str, sym: SymbolicState) -> None:
        """Re-compute clearance profile for obj_id and update symbolic state."""
        obj = self._registry.get_object(obj_id)
        if obj is None:
            return

        profile = obj.clearance_profile
        if profile is None:
            # No profile stored on registry object — skip geometric update
            self._log.debug(
                "[PostDisplacementHook] %s has no clearance_profile, skipping reground", obj_id
            )
            return

        score = profile.graspability_score
        has_viable = profile.has_viable_approach

        # Update access-clear
        if score > _GRASPABILITY_THRESHOLD and has_viable:
            sym.add("access-clear", obj_id)
            sym.add("checked-access-clear", obj_id)
            self._log.info(
                "[PostDisplacementHook] %s: access-clear=TRUE (score=%.2f)", obj_id, score
            )
        else:
            sym.remove("access-clear", obj_id)
            sym.add("checked-access-clear", obj_id)
            self._log.info(
                "[PostDisplacementHook] %s: access-clear=FALSE (score=%.2f)", obj_id, score
            )

        # Update obstructs predicates from blocked corridors
        blocking_set: Set[str] = set()
        for corridor in profile.approach_corridors:
            if not corridor.grasp_compatible:
                blocking_set.update(corridor.obstructing_objects)

        for blocker_id in blocking_set:
            sym.add("obstructs", blocker_id, obj_id)
            sym.add("checked-obstructs", blocker_id, obj_id)
            self._log.debug(
                "[PostDisplacementHook] obstructs(%s, %s)=TRUE", blocker_id, obj_id
            )

    def _plan_still_valid(
        self, sym: SymbolicState, remaining_plan: List[str]
    ) -> bool:
        """Check if remaining plan steps have their checked-* preconditions satisfied.

        For each check-* action in the remaining plan, if the corresponding
        checked-* predicate is absent from the symbolic state the plan is
        invalid — a sensing action will need to re-run before the manipulation.
        This is not a hard failure; it signals that replanning is preferred.
        """
        for action_str in remaining_plan:
            try:
                s = action_str.strip().strip("()")
                tokens = s.split()
                action_name = tokens[0].lower() if tokens else ""
                args = tokens[1:]
            except Exception:
                continue
            if not action_name.startswith("check-"):
                continue
            pred_name = action_name[len("check-"):]
            checked_pred = f"checked-{pred_name}"
            if args and sym.contains(checked_pred, *args):
                # Already checked and still in symbolic state — potentially stale
                # after a spatial change; conservatively flag as invalid
                self._log.debug(
                    "[PostDisplacementHook] %s stale after displacement — replan preferred",
                    action_str,
                )
                return False
        return True


# ---------------------------------------------------------------------------
# ClutterGrounder — evaluates grounding rules against live Ψ
# ---------------------------------------------------------------------------

class ClutterGrounder:
    """Evaluates clutter predicate grounding rules against a Ψ snapshot.

    The grounder reads from the registry's contact_graph, occlusion_map,
    and per-object clearance_profile fields.

    All sensed predicates are returned as FALSE (per §3.3 conservative init).
    Only `stable-on` (an object_state predicate) is returned as TRUE when
    the contact graph confirms a supporting relationship.

    Usage:
        grounder = ClutterGrounder(registry)
        true_facts  = grounder.ground_stable_on()   # for L5 :init
        false_facts = grounder.ground_sensed_false() # conservative FALSE set
    """

    def __init__(self, registry: "DetectedObjectRegistry") -> None:
        self._registry = registry
        # Tracks graspability scores from the previous evaluation cycle.
        # Used by evaluate_improved_clearance to detect improvement direction.
        self._previous_graspability: Dict[str, float] = {}

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def ground_stable_on(self) -> List[Tuple[str, List[str]]]:
        """Return TRUE (stable-on ?obj ?surface) facts from the contact graph.

        Covers supporting contact type where the lower object is a surface
        type (table, shelf, etc.).
        """
        graph = self._registry.contact_graph
        if graph is None:
            logger.warning("ground_stable_on: contact_graph is None — skipping contact-based facts")
            return []

        all_objects = self._registry.get_all_objects()
        surface_ids: Set[str] = {
            obj.object_id
            for obj in all_objects
            if any(kw in obj.object_type.lower() for kw in _SURFACE_KEYWORDS)
        }
        logger.info(
            "ground_stable_on: %d objects, %d surface_ids=%s, %d edges, support_tree keys=%s",
            len(all_objects),
            len(surface_ids),
            sorted(surface_ids),
            len(graph.edges),
            sorted(graph.support_tree.keys()),
        )
        for edge in graph.edges:
            logger.info(
                "  edge: %s --%s--> %s",
                edge.obj_a, edge.contact_type, edge.obj_b,
            )

        facts: List[Tuple[str, List[str]]] = []
        for lower_id, upper_ids in graph.support_tree.items():
            if lower_id not in surface_ids:
                logger.info(
                    "ground_stable_on: support_tree key %s not in surface_ids — skipping",
                    lower_id,
                )
                continue
            for upper_id in upper_ids:
                facts.append(("stable-on", [upper_id, lower_id]))
                logger.debug("stable-on: %s on %s (from support_tree)", upper_id, lower_id)

        # Also check edges directly for supporting type
        seen: Set[Tuple[str, str]] = {(u, l) for _, [u, l] in facts}
        for edge in graph.edges:
            if edge.contact_type != "supporting":
                continue
            if edge.obj_a not in surface_ids:
                continue
            key = (edge.obj_b, edge.obj_a)
            if key not in seen:
                facts.append(("stable-on", [edge.obj_b, edge.obj_a]))
                seen.add(key)
                logger.debug(
                    "stable-on: %s on %s (from edge type=%s)",
                    edge.obj_b, edge.obj_a, edge.contact_type,
                )

        # Fallback: any non-surface object not yet placed gets assigned to the
        # nearest surface below it by Z coordinate.  Without this, objects whose
        # contact was not detected are unplaceable and the problem is unsolvable.
        placed_ids: Set[str] = {uid for _, [uid, _] in facts}
        surface_objs = [o for o in all_objects if o.object_id in surface_ids]
        non_surface_objs = [
            o for o in all_objects
            if o.object_id not in surface_ids and o.object_id not in placed_ids
        ]

        if surface_objs and non_surface_objs:
            import numpy as np
            for obj in non_surface_objs:
                if obj.position_3d is None:
                    # No 3D position — assign to the first surface as best guess.
                    surf = surface_objs[0]
                    facts.append(("stable-on", [obj.object_id, surf.object_id]))
                    logger.debug(
                        "stable-on: %s on %s (fallback — no position)",
                        obj.object_id, surf.object_id,
                    )
                    continue

                obj_z = float(np.asarray(obj.position_3d)[2])
                best_surf = None
                best_dz = float("inf")
                for surf in surface_objs:
                    if surf.position_3d is None:
                        continue
                    surf_z = float(np.asarray(surf.position_3d)[2])
                    dz = obj_z - surf_z
                    # Surface must be below the object (dz > 0) and as close as possible.
                    if 0 <= dz < best_dz:
                        best_dz = dz
                        best_surf = surf
                if best_surf is None:
                    # Object is below all surfaces or all surfaces lack position — pick first.
                    best_surf = surface_objs[0]
                facts.append(("stable-on", [obj.object_id, best_surf.object_id]))
                logger.debug(
                    "stable-on: %s on %s (fallback — proximity dz=%.3f)",
                    obj.object_id, best_surf.object_id, best_dz,
                )

        return facts

    def ground_sensed_false(
        self, object_ids: Optional[List[str]] = None
    ) -> List[Tuple[str, List[str]]]:
        """Return conservative FALSE entries for all sensed clutter predicates.

        All sensed predicates are initialized FALSE (§3.3) — the planner must
        schedule sensing actions before relying on them.

        Args:
            object_ids: Restrict to this subset of object IDs.  Defaults to
                all objects in the registry.

        Returns:
            List of (predicate_name, [arg1, ...]) tuples, all FALSE.
        """
        all_objects = self._registry.get_all_objects()
        if object_ids is not None:
            id_set = set(object_ids)
            all_objects = [o for o in all_objects if o.object_id in id_set]

        obj_ids = [o.object_id for o in all_objects]
        surface_ids = [
            o.object_id for o in all_objects
            if any(kw in o.object_type.lower() for kw in _SURFACE_KEYWORDS)
        ]
        non_surface_ids = [o for o in obj_ids if o not in surface_ids]

        false_facts: List[Tuple[str, List[str]]] = []

        # Unary sensed predicates over all objects
        for pred in ("access-clear", "displaceable", "removal-safe", "visible", "improved-clearance"):
            for oid in obj_ids:
                false_facts.append((pred, [oid]))

        # Binary sensed predicates: obstructs(?blocker, ?target) — all pairs
        for blocker in obj_ids:
            for target in obj_ids:
                if blocker != target:
                    false_facts.append(("obstructs", [blocker, target]))

        # space-available(?surface, ?obj) — surface × non-surface
        for sid in surface_ids:
            for oid in non_surface_ids:
                false_facts.append(("space-available", [sid, oid]))

        # supports(?lower, ?upper) — all pairs
        for lower in obj_ids:
            for upper in obj_ids:
                if lower != upper:
                    false_facts.append(("supports", [lower, upper]))

        # occluded-by(?target, ?blocker) — all pairs
        for target in obj_ids:
            for blocker in obj_ids:
                if target != blocker:
                    false_facts.append(("occluded-by", [target, blocker]))

        return false_facts

    def evaluate_access_clear(self, obj_id: str) -> bool:
        """§3.2: graspability_score > 0.5 AND any grasp_compatible corridor."""
        obj = self._registry.get_object(obj_id)
        if obj is None or obj.clearance_profile is None:
            return False
        profile = obj.clearance_profile
        # Snapshot score before returning so improved-clearance can compare
        self._previous_graspability[obj_id] = profile.graspability_score
        return (
            profile.graspability_score > _GRASPABILITY_THRESHOLD
            and any(c.grasp_compatible for c in profile.approach_corridors)
        )

    def evaluate_improved_clearance(self, obj_id: str) -> bool:
        """§3.3: 0.3 < graspability_score < 0.5 AND score > previous score.

        Signals that a push-aside or partial displacement improved access
        but did not yet reach the access-clear threshold.  Allows the planner
        to issue a second recovery action rather than replanning from scratch.
        """
        obj = self._registry.get_object(obj_id)
        if obj is None or obj.clearance_profile is None:
            return False
        score = obj.clearance_profile.graspability_score
        prev = self._previous_graspability.get(obj_id, 0.0)
        self._previous_graspability[obj_id] = score
        return _IMPROVED_CLEARANCE_LOW < score < _IMPROVED_CLEARANCE_HIGH and score > prev

    def evaluate_obstructs(self, blocker_id: str, target_id: str) -> bool:
        """§3.2: blocker appears in obstructing_objects of any blocked corridor."""
        obj = self._registry.get_object(target_id)
        if obj is None or obj.clearance_profile is None:
            return False
        for corridor in obj.clearance_profile.approach_corridors:
            if corridor.grasp_compatible:
                continue
            if hasattr(corridor, "obstructing_objects") and blocker_id in corridor.obstructing_objects:
                return True
        return False

    def evaluate_displaceable(self, obj_id: str) -> bool:
        """§3.2: removal_consequence is not cascade (object can be safely removed)."""
        graph = self._registry.contact_graph
        if graph is None:
            return True  # no graph yet — assume displaceable
        consequence = graph.removal_consequences.get(obj_id, "stable")
        return consequence != "cascade"

    def evaluate_space_available(self, surface_id: str, obj_id: str) -> bool:  # noqa: ARG002
        """Return the LLM-assigned room_available flag for this surface.

        Surface-map geometry is no longer computed; the LLM assesses whether the
        surface visually has room when it classifies contacts.  Defaults to True
        when no assessment exists (executor grounds placement pose at runtime).
        """
        graph = self._registry.contact_graph
        if graph is None:
            return True  # no graph yet — assume space available
        return graph.room_available.get(surface_id, True)

    def evaluate_supports(self, lower_id: str, upper_id: str) -> bool:
        """§3.2: (lower, upper) in contact_graph.support_tree."""
        graph = self._registry.contact_graph
        if graph is None:
            return False
        return upper_id in graph.support_tree.get(lower_id, [])

    def evaluate_removal_safe(self, obj_id: str) -> bool:
        """§3.2: removal_consequence == stable."""
        graph = self._registry.contact_graph
        if graph is None:
            return False
        return graph.removal_consequences.get(obj_id, "stable") == "stable"

    def evaluate_visible(self, obj_id: str) -> bool:
        """§3.2: visible_fraction > 0.6."""
        occ = self._registry.occlusion_map
        if occ is None:
            return False
        vis = occ.per_object_visibility.get(obj_id)
        if vis is None:
            return False
        return vis.visible_fraction > _VISIBILITY_THRESHOLD

    def evaluate_occluded_by(self, target_id: str, blocker_id: str) -> bool:
        """§3.2: blocker in per_object_visibility[target].occluding_objects."""
        occ = self._registry.occlusion_map
        if occ is None:
            return False
        vis = occ.per_object_visibility.get(target_id)
        if vis is None:
            return False
        return blocker_id in vis.occluding_objects

    def ground_all(self) -> Dict[str, List[Tuple[str, List[str]]]]:
        """Evaluate all grounding rules and return TRUE/FALSE fact dictionaries.

        Returns:
            {"true": [...], "false": [...]} — each entry is (pred_name, [args]).
            Sensed predicates are always in "false" per §3.3 conservative init.
            stable-on TRUE facts are placed in "true".
        """
        return {
            "true": self.ground_stable_on(),
            "false": self.ground_sensed_false(),
        }
