"""
Clutter Domain Module — L2 Predicate Vocabulary and Grounding Rules

Pre-loads the clutter manipulation predicate library into the DKB and
provides a ClutterGrounder that evaluates each predicate's grounding rule
against a live Ψ snapshot (DetectedObjectRegistry + per-object perception
outputs).

Usage
-----
    from src.planning.clutter_module import load_clutter_module, ClutterGrounder

    # Once at startup — idempotent, safe to call again after DKB reload
    load_clutter_module(dkb)

    # Each planning cycle, after perception has updated Ψ
    grounder = ClutterGrounder(registry)
    true_facts = grounder.ground_all()
    # → [("stable-on", ["red_block_1", "table_1"]), ...]

Predicate catalogue (§3.1)
--------------------------
Sensed (conservative FALSE until check-X sensing action runs):
    access-clear(?obj)
    obstructs(?blocker, ?target)
    displaceable(?obj)
    space-available(?surface, ?obj)
    supports(?lower, ?upper)
    removal-safe(?obj)
    visible(?obj)
    occluded-by(?target, ?blocker)

State (grounded directly from Ψ at L5 init):
    stable-on(?obj, ?surface)

Each sensed predicate has a corresponding checked-* variant auto-generated
by _repair_l2_auto() in LayeredDomainGenerator — not listed here.
"""

from __future__ import annotations

import logging
from typing import TYPE_CHECKING, Dict, List, Optional, Set, Tuple

if TYPE_CHECKING:
    from ..perception.object_registry import DetectedObjectRegistry

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Threshold constants matching §3.2 grounding rules
# ---------------------------------------------------------------------------

_GRASPABILITY_THRESHOLD: float = 0.5    # access-clear: graspability_score >
_VISIBILITY_THRESHOLD: float = 0.6      # visible: visible_fraction >
_STABILITY_THRESHOLD: float = 0.7       # displaceable: stability_score >

# ---------------------------------------------------------------------------
# Clutter module predicate definitions
# ---------------------------------------------------------------------------

# Each entry: (name, signature, type_classification, grounding_rule_summary)
_CLUTTER_PREDICATES: List[Tuple[str, str, str, str]] = [
    # Access / obstruction
    (
        "access-clear",
        "(?obj - object)",
        "sensed",
        "graspability_score > 0.5 AND any grasp_compatible corridor",
    ),
    (
        "obstructs",
        "(?blocker - object ?target - object)",
        "sensed",
        "?blocker in obstructing_objects of any blocked corridor of ?target",
    ),
    (
        "displaceable",
        "(?obj - object)",
        "sensed",
        "stability_score > 0.7 AND removal_consequence != cascade",
    ),
    # Placement
    (
        "space-available",
        "(?surface - surface ?obj - object)",
        "sensed",
        "any free_region.max_inscribed_circle >= obj footprint radius",
    ),
    # Stability / support
    (
        "supports",
        "(?lower - object ?upper - object)",
        "sensed",
        "(?lower, ?upper) in contact_graph.support_tree",
    ),
    (
        "removal-safe",
        "(?obj - object)",
        "sensed",
        "contact_graph.removal_consequences[?obj] == stable",
    ),
    (
        "stable-on",
        "(?obj - object ?surface - surface)",
        "object_state",
        "contact_graph supporting edge from ?surface to ?obj",
    ),
    # Visibility
    (
        "visible",
        "(?obj - object)",
        "sensed",
        "occlusion_map.per_object_visibility[?obj].visible_fraction > 0.6",
    ),
    (
        "occluded-by",
        "(?target - object ?blocker - object)",
        "sensed",
        "?blocker in occlusion_map.per_object_visibility[?target].occluding_objects",
    ),
]

# Sensed predicates that need checked-* variants (auto-generated by L2 repair)
CLUTTER_SENSED_PREDICATE_NAMES: List[str] = [
    entry[0] for entry in _CLUTTER_PREDICATES
    if entry[2] == "sensed"
]


# ---------------------------------------------------------------------------
# DKB loader
# ---------------------------------------------------------------------------

def load_clutter_module(dkb: "DomainKnowledgeBase") -> None:  # type: ignore[name-defined]
    """Load the clutter predicate library into the DKB predicate store.

    Idempotent — existing entries are updated in place (usage_count preserved).
    Call once at startup after dkb.load().

    Args:
        dkb: A DomainKnowledgeBase instance (already loaded).
    """
    loaded = 0
    for name, params, cls, rule in _CLUTTER_PREDICATES:
        sig = f"({name} {params})" if params else f"({name})"
        existing = dkb._predicates.get(name, {})
        dkb._predicates[name] = {
            "signature": sig,
            "type_classification": cls,
            "grounding_rule": rule,
            "domain_module": "clutter",
            "usage_count": existing.get("usage_count", 0),
            "last_task": existing.get("last_task", ""),
        }
        loaded += 1

    logger.info("load_clutter_module: loaded %d predicate definitions into DKB", loaded)


def get_clutter_predicate_signatures() -> List[str]:
    """Return full PDDL-style signatures for all clutter predicates."""
    return [
        f"({name} {params})" if params else f"({name})"
        for name, params, _, _ in _CLUTTER_PREDICATES
    ]


def get_clutter_type_classifications() -> Dict[str, str]:
    """Return {predicate_name: type_classification} for all clutter predicates."""
    return {name: cls for name, _, cls, _ in _CLUTTER_PREDICATES}


# ---------------------------------------------------------------------------
# ClutterGrounder — evaluates grounding rules against live Ψ
# ---------------------------------------------------------------------------

class ClutterGrounder:
    """Evaluates clutter predicate grounding rules against a Ψ snapshot.

    The grounder reads from the registry's contact_graph, occlusion_map,
    and per-object clearance_profile / surface_map fields.

    All sensed predicates are returned as FALSE (per §3.3 conservative init).
    Only `stable-on` (an object_state predicate) is returned as TRUE when
    the contact graph confirms a supporting relationship.

    Usage:
        grounder = ClutterGrounder(registry)
        true_facts  = grounder.ground_stable_on()   # for L5 :init
        false_facts = grounder.ground_sensed_false() # conservative FALSE set
    """

    def __init__(self, registry: "DetectedObjectRegistry") -> None:
        self._registry = registry

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def ground_stable_on(self) -> List[Tuple[str, List[str]]]:
        """Return TRUE (stable-on ?obj ?surface) facts from the contact graph.

        Covers supporting contact type where the lower object is a surface
        type (table, shelf, etc.).
        """
        graph = self._registry.contact_graph
        if graph is None:
            return []

        surface_ids: Set[str] = {
            obj.object_id
            for obj in self._registry.get_all_objects()
            if obj.object_type.lower() in (
                "surface", "table", "shelf", "tray", "counter", "desk"
            )
        }

        facts: List[Tuple[str, List[str]]] = []
        for lower_id, upper_ids in graph.support_tree.items():
            if lower_id not in surface_ids:
                continue
            for upper_id in upper_ids:
                facts.append(("stable-on", [upper_id, lower_id]))
                logger.debug("stable-on: %s on %s (from support_tree)", upper_id, lower_id)

        # Also check edges directly for supporting type
        seen: Set[Tuple[str, str]] = {(u, l) for _, [u, l] in facts}
        for edge in graph.edges:
            if edge.contact_type != "supporting":
                continue
            if edge.obj_a not in surface_ids:
                continue
            key = (edge.obj_b, edge.obj_a)
            if key not in seen:
                facts.append(("stable-on", [edge.obj_b, edge.obj_a]))
                seen.add(key)
                logger.debug(
                    "stable-on: %s on %s (from edge type=%s)",
                    edge.obj_b, edge.obj_a, edge.contact_type,
                )

        return facts

    def ground_sensed_false(
        self, object_ids: Optional[List[str]] = None
    ) -> List[Tuple[str, List[str]]]:
        """Return conservative FALSE entries for all sensed clutter predicates.

        All sensed predicates are initialized FALSE (§3.3) — the planner must
        schedule sensing actions before relying on them.

        Args:
            object_ids: Restrict to this subset of object IDs.  Defaults to
                all objects in the registry.

        Returns:
            List of (predicate_name, [arg1, ...]) tuples, all FALSE.
        """
        all_objects = self._registry.get_all_objects()
        if object_ids is not None:
            id_set = set(object_ids)
            all_objects = [o for o in all_objects if o.object_id in id_set]

        obj_ids = [o.object_id for o in all_objects]
        surface_ids = [
            o.object_id for o in all_objects
            if o.object_type.lower() in (
                "surface", "table", "shelf", "tray", "counter", "desk"
            )
        ]
        non_surface_ids = [o for o in obj_ids if o not in surface_ids]

        false_facts: List[Tuple[str, List[str]]] = []

        # Unary sensed predicates over all objects
        for pred in ("access-clear", "displaceable", "removal-safe", "visible"):
            for oid in obj_ids:
                false_facts.append((pred, [oid]))

        # Binary sensed predicates: obstructs(?blocker, ?target) — all pairs
        for blocker in obj_ids:
            for target in obj_ids:
                if blocker != target:
                    false_facts.append(("obstructs", [blocker, target]))

        # space-available(?surface, ?obj) — surface × non-surface
        for sid in surface_ids:
            for oid in non_surface_ids:
                false_facts.append(("space-available", [sid, oid]))

        # supports(?lower, ?upper) — all pairs
        for lower in obj_ids:
            for upper in obj_ids:
                if lower != upper:
                    false_facts.append(("supports", [lower, upper]))

        # occluded-by(?target, ?blocker) — all pairs
        for target in obj_ids:
            for blocker in obj_ids:
                if target != blocker:
                    false_facts.append(("occluded-by", [target, blocker]))

        return false_facts

    def evaluate_access_clear(self, obj_id: str) -> bool:
        """§3.2: graspability_score > 0.5 AND any grasp_compatible corridor."""
        obj = self._registry.get_object(obj_id)
        if obj is None or obj.clearance_profile is None:
            return False
        profile = obj.clearance_profile
        return (
            profile.graspability_score > _GRASPABILITY_THRESHOLD
            and any(c.grasp_compatible for c in profile.approach_corridors)
        )

    def evaluate_obstructs(self, blocker_id: str, target_id: str) -> bool:
        """§3.2: blocker appears in obstructing_objects of any blocked corridor."""
        obj = self._registry.get_object(target_id)
        if obj is None or obj.clearance_profile is None:
            return False
        for corridor in obj.clearance_profile.approach_corridors:
            if corridor.grasp_compatible:
                continue
            if hasattr(corridor, "obstructing_objects") and blocker_id in corridor.obstructing_objects:
                return True
        return False

    def evaluate_displaceable(self, obj_id: str) -> bool:
        """§3.2: stability_score > 0.7 AND removal_consequence != cascade."""
        graph = self._registry.contact_graph
        if graph is None:
            return False
        score = graph.stability_scores.get(obj_id, 0.0)
        consequence = graph.removal_consequences.get(obj_id, "stable")
        return score > _STABILITY_THRESHOLD and consequence != "cascade"

    def evaluate_space_available(self, surface_id: str, obj_id: str) -> bool:
        """§3.2: any free_region.max_inscribed_circle >= obj footprint radius."""
        from ..perception.surface_map import can_place
        surface_obj = self._registry.get_object(surface_id)
        if surface_obj is None or surface_obj.surface_map is None:
            return False
        all_objects = self._registry.get_all_objects()
        surface_maps = {surface_id: surface_obj.surface_map}
        feasible, _ = can_place(obj_id, surface_id, surface_maps, all_objects)
        return feasible

    def evaluate_supports(self, lower_id: str, upper_id: str) -> bool:
        """§3.2: (lower, upper) in contact_graph.support_tree."""
        graph = self._registry.contact_graph
        if graph is None:
            return False
        return upper_id in graph.support_tree.get(lower_id, [])

    def evaluate_removal_safe(self, obj_id: str) -> bool:
        """§3.2: removal_consequence == stable."""
        graph = self._registry.contact_graph
        if graph is None:
            return False
        return graph.removal_consequences.get(obj_id, "stable") == "stable"

    def evaluate_visible(self, obj_id: str) -> bool:
        """§3.2: visible_fraction > 0.6."""
        occ = self._registry.occlusion_map
        if occ is None:
            return False
        vis = occ.per_object_visibility.get(obj_id)
        if vis is None:
            return False
        return vis.visible_fraction > _VISIBILITY_THRESHOLD

    def evaluate_occluded_by(self, target_id: str, blocker_id: str) -> bool:
        """§3.2: blocker in per_object_visibility[target].occluding_objects."""
        occ = self._registry.occlusion_map
        if occ is None:
            return False
        vis = occ.per_object_visibility.get(target_id)
        if vis is None:
            return False
        return blocker_id in vis.occluding_objects

    def ground_all(self) -> Dict[str, List[Tuple[str, List[str]]]]:
        """Evaluate all grounding rules and return TRUE/FALSE fact dictionaries.

        Returns:
            {"true": [...], "false": [...]} — each entry is (pred_name, [args]).
            Sensed predicates are always in "false" per §3.3 conservative init.
            stable-on TRUE facts are placed in "true".
        """
        return {
            "true": self.ground_stable_on(),
            "false": self.ground_sensed_false(),
        }
